version: '2.3'

networks:
  frontend:
    external: true
  mochi_backend:
    internal: true

services:
  web:
    build: .
    image: mochi-web
    container_name: mochi_web
    restart: always
    networks:
      - frontend
      - mochi_backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.mochi.loadbalancer.server.port=8080"
      - "traefik.http.routers.mochi.rule=Host(`mochi.cloud.themaymeow.com`)"
      - "traefik.http.routers.mochi.entrypoints=websecure"
      - "traefik.http.routers.mochi.tls.certresolver=le"
      - "traefik.docker.network=frontend"